### ISSUE TITLE
[bug] Fix Application crush when My page option button clicked

### ISSUE THREAD

**Issue by DongJun-H** [Daily-DAYO/DAYO_Android#400]
**버그 세부사항**
- 마이페이지에서 상단 액션바의 옵션버튼을 클릭하면 예외 발견으로 강제 종료되는 현상

**버그 발생 환경**
- 화면 클릭위치 나타남
- 재현 영상: https://github.com/Daily-DAYO/DAYO_Android/assets/65344669/db959c1d-53a0-4be5-9abc-5a56fe01d1c1

**버그로 인한 결과**
- 앱 강제종료

**Smartphone (please complete the following information):**
 - Device: 갤럭시S22 Ultra
 - OS: Android 13
 - Version 1.0

**추가 세부 사항 및 조치**
- 다른 사람의 프로필로 들어가 옵션버튼을 누른뒤에 돌아와 마이페이지의 옵션버튼을 클릭하면 강제종료되지 않고 정상적으로 작동됨
- 매번 앱을 켜고 끌때마다 발생

**Comment by gemiJ** [comment]
확인한다고 온갖버튼 눌러서 실행했었는데도 잘못된 부분이 있었네요ㅠㅠ 
바로 수정하겠습니다 ^^7
